/*
* generated by Xtext
*/
package fr.unice.spinefm;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RestfuncDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.unice.spinefm.ui.internal.RestfuncDSLActivator.getInstance().getInjector("fr.unice.spinefm.RestfuncDSL");
	}
	
}
