/*
* generated by Xtext
*/
package fr.unice.spinefm.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractRestfuncDSLJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.unice.spinefm.restfuncDSL.RestfuncDSLPackage.eINSTANCE);
		return result;
	}

}
