/*
* generated by Xtext
*/
package fr.unice.spinefm.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RestfuncDSLProposalProvider extends fr.unice.spinefm.ui.contentassist.AbstractRestfuncDSLProposalProvider {

}
