/*
 * generated by Xtext
 */
package fr.unice.spinefm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RestfuncDSLRuntimeModule extends fr.unice.spinefm.AbstractRestfuncDSLRuntimeModule {

}
