/*
* generated by Xtext
*/
package fr.unice.spinefm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RestfuncDSLStandaloneSetup extends RestfuncDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new RestfuncDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

