/*
 * generated by Xtext
 */
package fr.unice.spinefm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RestfuncDSLUiModule extends fr.unice.spinefm.ui.AbstractRestfuncDSLUiModule {
	public RestfuncDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
