/*
* generated by Xtext
*/
package fr.unice.spinefm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.unice.spinefm.services.RestfuncDSLGrammarAccess;

public class RestfuncDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RestfuncDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.unice.spinefm.parser.antlr.internal.InternalRestfuncDSLParser createParser(XtextTokenStream stream) {
		return new fr.unice.spinefm.parser.antlr.internal.InternalRestfuncDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RestFunc";
	}
	
	public RestfuncDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RestfuncDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
