/*
* generated by Xtext
*/
package fr.unice.spinefm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RestfuncDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/unice/spinefm/parser/antlr/internal/InternalRestfuncDSL.tokens");
	}
}
