/*
 * generated by Xtext
 */
package fr.unice.spinefm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.unice.spinefm.ui.internal.RestfuncDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestfuncDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RestfuncDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RestfuncDSLActivator.getInstance().getInjector(RestfuncDSLActivator.FR_UNICE_SPINEFM_RESTFUNCDSL);
	}
	
}
